// Materias específicas — Clase A, Categoría II-A (24 preguntas oficiales, RNV/RENAT)
const ESPECIFICAS_2A = [
{id:30001,q:"El Reglamento Nacional de Administración de Transporte regula:",o:["El servicio de transporte terrestre y el tránsito.","El servicio de transporte terrestre de personas y mercancías.","Únicamente el servicio de transporte de mercancías.","Ninguna de las anteriores."],a:1},
{id:30002,q:"El régimen o la actividad de fiscalización no está orientada a:",o:["Proteger la vida, la salud y la seguridad de las personas.","Proteger los intereses de los usuarios y de los prestadores del servicio.","Sancionar los incumplimientos o infracciones previstas en el Reglamento Nacional de Administración de Transporte","Promover la inclusión social."],a:3},
{id:30003,q:"Las sanciones por las infracciones al servicio de transporte se encuentran comprendidas en:",o:["El Reglamento Nacional de Administración de Transporte.","El Texto Único Ordenado del Reglamento Nacional de Tránsito - Código de Tránsito.","El Reglamento Nacional de Inspecciones Técnicas Vehiculares.","Todas las anteriores."],a:0},
{id:30004,q:"Con relación a las obligaciones del conductor del servicio de transporte terrestre. Marque la alternativa incorrecta:",o:["Debe ser titular de una licencia de conducir de la clase y categoría que corresponda al vehículo que conduce.","Debe portar su licencia de conducir vigente, así como la documentación del vehículo.","Debe conducir solo vehículos habilitados por la autoridad competente.","Puede oponerse a la labor de supervisión y fiscalización de la autoridad competente."],a:3},
{id:30005,q:"Con relación a las obligaciones del conductor del servicio de transporte terrestre, es obligatorio que el conductor ….",o:["No deba tener su licencia de conducir suspendida, retenida o cancelada","No deba llegar o exceder de tope máximo de 100 puntos firmes","No tenga impuesta dos o más infracciones Muy Graves, cinco o más infracciones Graves o una infracción Muy Grave y tres o más infracciones Graves","Todas las anteriores."],a:3},
{id:30006,q:"La entidad competente de fiscalizar el servicio de transporte de ámbito provincial es:",o:["El Gobierno Regional.","La municipalidad provincial.","El Ministerio de Transportes y Comunicaciones.","\"a\" y \"c\" son correctas."],a:1},
{id:30007,q:"Las infracciones se clasifican de acuerdo a su gradualidad en:",o:["Levísimas, graves y gravísimas.","Leves, graves y muy graves.","Leves, graves, muy graves y gravísimas.","Levísimas, gravísimas y muy graves."],a:1},
{id:30008,q:"La edad máxima para conducir vehículos destinados al servicio de transporte terrestre es de:",o:["55 años.","60 años.","65 años.","70 años."],a:3},
{id:30009,q:"El servicio de transporte especial de personas es aquel que se presta:",o:["Sin regularidad ni uniformidad.","Con regularidad y uniformidad.","Sin regularidad y con uniformidad.","Con regularidad y sin uniformidad"],a:0},
{id:30010,q:"La autorización del servicio de taxi habilita para:",o:["Prestar el servicio dentro de la respectiva provincia donde se otorgó la autorización.","Prestar el servicio en todo el ámbito nacional.","Prestar el servicio dentro de todo el departamento correspondiente a la provincia donde se otorgó la autorización.","Ninguna de las anteriores."],a:0},
{id:30011,q:"¿Cuál de los siguientes servicios no corresponde al servicio de transporte especial de personas?",o:["Diferenciado.","Turístico.","De trabajadores.","De estudiantes."],a:0},
{id:30012,q:"Si un conductor atenta contra la integridad física del inspector durante la realización de sus funciones, será sancionado con:",o:["Cancelación de licencia de conducir e inhabilitación para obtener nueva licencia por tres (3) años.","Suspensión de la licencia de conducir por tres (3) años.","Cancelación de la licencia de conducir e inhabilitación definitiva para obtener nueva licencia. Multa de 0.5 UIT.","Cancelación de la licencia de conducir por un (1) año e inhabilitación definitiva para obtener nueva licencia. Multa de 1 UIT."],a:2},
{id:30013,q:"El vehículo que prestan el servicio de transporte provincial de personas debe contar con el siguiente Seguro:",o:["Únicamente con el Seguro Obligatorio de Accidentes de Tránsito- SOAT.","Únicamente con el Certificado de Accidentes de Tránsito - CAT.","El Seguro Obligatorio de Accidentes de Tránsito - SOAT o el Certificado contra Accidentes de tránsito - CAT.","Ninguno de los anteriores."],a:2},
{id:30014,q:"En el servicio de transporte la vigencia de la habilitación del conductor es ….y de renovación automática una vez acreditada la vigencia de la licencia de conducir de la categoría correspondiente al vehículo habilitado",o:["Anual.","cada dos años.","Cada cinco años.","Ninguna de las anteriores."],a:0},
{id:30015,q:"¿A partir de qué edad el conductor del servicio de transporte deberá rendir y aprobar los exámenes médicos semestrales que establezca la Dirección General de Transporte Terrestre (DGTT)?",o:["60 años.","55 años.","65 años.","No existe dicho exigencia en la norma."],a:2},
{id:30016,q:"Si un presunto infractor paga voluntariamente dentro de los cinco días hábiles de levantada el acta de control, la multa que corresponda a la infracción imputada, ésta será reducida en:",o:["20% de su monto.","30% de su monto.","40% de su monto.","50% de su monto."],a:3},
{id:30017,q:"Cuando hablamos del «servicio de transporte especial de ámbito provincial, prestado en vehículos M1 de la clasificación vehicular, que tiene por objeto el traslado de personas desde un punto de origen hasta un punto de destino señalado por quien lo contrata.», nos estamos refiriendo al:",o:["Servicio de transporte de trabajadores.","Servicio de transporte de mercancías.","Servicio de transporte de taxi.","Servicio de transporte turístico."],a:2},
{id:30018,q:"Es la medida preventiva que consiste en el traslado del vehículo fuera de la vía pública dispuesto por la autoridad competente y/o PNP, utilizando cualquier medio eficaz y proporcional al fin que se persigue:",o:["Remoción del vehículo.","Retención del vehículo.","Internamiento del vehículo.","Interrupción del viaje."],a:0},
{id:30019,q:"El servicio de transporte debe ser prestado a través de vehículos que:",o:["Se encuentren habilitados.","Hayan aprobado la Inspección Técnica Vehicular, cuando corresponda.","Cuenten con póliza de Seguro Obligatorio de Accidentes de Tránsito vigente o Certificado Contra Accidentes de Tránsito, según corresponda.","Todas las anteriores."],a:3},
{id:30020,q:"¿Qué sanción le corresponde al conductor que presta el servicio sin contar con autorización otorgada por la autoridad competente o en una modalidad o ámbito diferente al autorizado?",o:["Multa de 1 UIT","Multa de 2 UIT","Multa de 0.5 UIT","Multa de 0.05 UIT"],a:0},
{id:30021,q:"En cual de los siguientes supuestos no corresponde la medida preventiva de retención de la licencia de conducir, en el servicio de transporte terrestre:",o:["Por negarse a entregar información o documentación correspondiente al vehículo que conduce.","Por realizar acciones destinadas a no someterse o a burlar la fiscalización.","Por desacatar la orden de suspensión precautoria del servicio de transporte.","Por conducir un vehículo que presta servicio de transporte, excediendo la edad máxima prevista en el Reglamento Nacional de Administración de Transporte"],a:2},
{id:30022,q:"La licencia de conducir de Clase A- Categoría II A tendrá una vigencia de…..",o:["3 años","5 años","8 años","2 años"],a:0},
{id:30023,q:"¿Cuál es la antigüedad mínima contando con licencia de Clase A- Categoría I que se requiere para obtener la licencia de Clase A categoría II A por recategorización?",o:["2 años.","4 años.","5 años","No existe antigüedad mínima"],a:0},
{id:30024,q:"La licencia de conducir de clase A categoría II A permite conducir los vehículos señalados en la categoría:",o:["I","III","IV","II B"],a:0},
];

if (typeof module !== "undefined") module.exports = ESPECIFICAS_2A;